// Generated by scripts/generate_ocr_contract.py. Do not edit.

export const OCR_EVENT_STAGES = [
  'discovery',
  'plan-validation',
  'overwrite-confirmation-required',
  'queued',
  'server-startup',
  'ocr-processing',
  'writing',
  'extracting',
  'persisting',
  'completed',
  'failed',
  'skipped',
  'progress',
  'job-finished',
  'job-failed'
] as const

export type OcrEventStage = (typeof OCR_EVENT_STAGES)[number]

export const OCR_JOB_STATUSES = [
  'pending',
  'discovering',
  'planning',
  'awaiting-overwrite',
  'overwrite-claimed',
  'overwrite-confirmed',
  'overwrite-declined',
  'starting-server',
  'running',
  'completed',
  'completed-with-errors',
  'failed',
  'interrupted'
] as const

export type OcrJobStatus = (typeof OCR_JOB_STATUSES)[number]

export const OCR_DOCUMENT_STATUSES = [
  'completed',
  'ocr-failed',
  'write-failed',
  'extract-failed',
  'processing-failed',
  'batch-failed'
] as const

export type OcrDocumentStatus = (typeof OCR_DOCUMENT_STATUSES)[number]

export const OCR_FILE_STAGES = [
  'queued',
  'awaiting-overwrite',
  'overwrite-claimed',
  'overwrite-confirmed',
  'overwrite-declined',
  'ocr-processing',
  'writing',
  'extracting',
  'persisting',
  'completed',
  'failed',
  'skipped',
  'interrupted'
] as const

export type OcrFileStage = (typeof OCR_FILE_STAGES)[number]

export const OCR_FILE_STATUSES = [
  'queued',
  'awaiting-overwrite',
  'overwrite-claimed',
  'overwrite-confirmed',
  'overwrite-declined',
  'running',
  'completed',
  'failed',
  'skipped',
  'interrupted'
] as const

export type OcrFileStatus = (typeof OCR_FILE_STATUSES)[number]
