from __future__ import annotations

import argparse
from enum import StrEnum
from pathlib import Path

from doc2webchat.ocr_contract import OCR_CONTRACT_ENUMS

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "frontend" / "src" / "api" / "ocr-contract.generated.ts"


def ts_constant_name(enum_type: type[StrEnum]) -> str:
    parts: list[str] = []
    current = ""
    for character in enum_type.__name__:
        if character.isupper() and current:
            parts.append(current.upper())
            current = character
        else:
            current += character
    parts.append(current.upper())
    name = "_".join(parts)
    return name[:-6] + "STATUSES" if name.endswith("_STATUS") else name + "S"


def render() -> str:
    lines = [
        "// Generated by scripts/generate_ocr_contract.py. Do not edit.",
        "",
    ]
    for enum_type in OCR_CONTRACT_ENUMS:
        constant = ts_constant_name(enum_type)
        lines.append(f"export const {constant} = [")
        members = list(enum_type)
        lines.extend(
            f"  '{member.value}'{',' if index < len(members) - 1 else ''}"
            for index, member in enumerate(members)
        )
        lines.extend(
            [
                "] as const",
                "",
                f"export type {enum_type.__name__} = (typeof {constant})[number]",
                "",
            ]
        )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    expected = render()
    if arguments.check:
        actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if actual != expected:
            print(
                "Generated OCR contract is stale. "
                "Run: uv run python scripts/generate_ocr_contract.py"
            )
            return 1
        return 0
    OUTPUT.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
